config/routes.rb
Rails.application.routes.draw do
  resources :components
  resources :arcades
  resources :orders
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arcade.rb
class Arcade < ApplicationRecord
  belongs_to :order
  has_many :component_arcade
  has_many :components, through: :component_arcade
end

app/controllers/arcades_controller.rb
class ArcadesController < ApplicationController
  before_action :set_arcade, only: [:show, :edit, :update, :destroy]

  # GET /arcades
  # GET /arcades.json
  def index
    @arcades = Arcade.all
  end

  # GET /arcades/1
  # GET /arcades/1.json
  def show
  end

  # GET /arcades/new
  def new
    @arcade = Arcade.new
  end

  # GET /arcades/1/edit
  def edit
  end

  # POST /arcades
  # POST /arcades.json
  def create
    @arcade = Arcade.new(arcade_params)

    respond_to do |format|
      if @arcade.save
        format.html { redirect_to @arcade, notice: 'Arcade was successfully created.' }
        format.json { render :show, status: :created, location: @arcade }
      else
        format.html { render :new }
        format.json { render json: @arcade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arcades/1
  # PATCH/PUT /arcades/1.json
  def update
    respond_to do |format|
      if @arcade.update(arcade_params)
        format.html { redirect_to @arcade, notice: 'Arcade was successfully updated.' }
        format.json { render :show, status: :ok, location: @arcade }
      else
        format.html { render :edit }
        format.json { render json: @arcade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arcades/1
  # DELETE /arcades/1.json
  def destroy
    @arcade.destroy
    respond_to do |format|
      format.html { redirect_to arcades_url, notice: 'Arcade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arcade
      @arcade = Arcade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arcade_params
      params.require(:arcade).permit(:name, :price, :order_id)
    end
end

app/helpers/arcades_helper.rb
module ArcadesHelper
end

app/views/arcades/_form.html.erb
<%= form_for(arcade) do |f| %>
  <% if arcade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arcade.errors.count, "error") %> prohibited this arcade from being saved:</h2>

      <ul>
      <% arcade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :order_id %>
    <%= f.text_field :order_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arcades/edit.html.erb
<h1>Editing Arcade</h1>

<%= render 'form', arcade: @arcade %>

<%= link_to 'Show', @arcade %> |
<%= link_to 'Back', arcades_path %>

app/views/arcades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arcades</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arcades.each do |arcade| %>
      <tr>
        <td><%= arcade.name %></td>
        <td><%= arcade.price %></td>
        <td><%= arcade.order %></td>
        <td><%= link_to 'Show', arcade %></td>
        <td><%= link_to 'Edit', edit_arcade_path(arcade) %></td>
        <td><%= link_to 'Destroy', arcade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arcade', new_arcade_path %>

app/views/arcades/new.html.erb
<h1>New Arcade</h1>

<%= render 'form', arcade: @arcade %>

<%= link_to 'Back', arcades_path %>

app/views/arcades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @arcade.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @arcade.price %>
</p>

<p>
  <strong>Order:</strong>
  <%= @arcade.order %>
</p>

<%= link_to 'Edit', edit_arcade_path(@arcade) %> |
<%= link_to 'Back', arcades_path %>